server:
    port: 8085
    servlet:
        context-path: "/auth"
logging:
    level:
        study.online.auth.controller: info
        study.online.ucenter.mapper: debug
spring:
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: 'http://localhost:8085/'