server:
    port: 8087
    servlet:
        context-path: '/learning'

logging:
    level:
        study.online.learning:
            mapper: debug
            service: info
            controller: info